workflows:
  - name: slow-checks-itde
    step_customizations:
      - action: INSERT_AFTER
        job: run-integration-tests
        step_id: check-out-repository
        content:
          - name: Allow unprivileged user namespaces
            id: allow-unprivileged-user-namespaces
            run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
      - action: REPLACE
        job: run-integration-tests
        step_id: run-integration-tests
        content:
          - name: Run Integration Tests
            id: run-integration-tests
            run: |
              JWK_URL=$(python -c "from test.utils.mcp_oidc_constants import DOCKER_JWK_URL; print(f'-oidcProviderJKU={DOCKER_JWK_URL}');")
              TOK_AUD=$(python -c "from test.utils.mcp_oidc_constants import TOKEN_AUDIENCE; print(f'-oidcProviderAUD={TOKEN_AUDIENCE}');")
              TOK_ISS=$(python -c "from test.utils.mcp_oidc_constants import TOKEN_ISSUER; print(f'-oidcProviderISS={TOKEN_ISSUER}');")
              poetry run -- nox -s test:integration -- -s --coverage --db-version ${{ matrix.exasol-version }} --backend=onprem --itde-additional-db-parameter="$JWK_URL" --itde-additional-db-parameter="$TOK_AUD" --itde-additional-db-parameter="$TOK_ISS"
  - name: slow-checks-saas
    step_customizations:
      - action: REPLACE
        job: run-integration-tests
        step_id: run-integration-tests
        content:
          - name: Run Integration Tests
            id: run-integration-tests
            env:
              SAAS_HOST: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_HOST }}
              SAAS_ACCOUNT_ID: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID }}
              SAAS_PAT: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_PAT }}
            run: poetry run -- nox -s test:integration -- -s --coverage --backend=saas
