OIDC_PORT = 25432
OIDC_USER_SUB = "test_sub"
OIDC_USER_NAME = "oidc_test_user"
DOCKER_NET_GATEWAY_IP = "172.25.0.1"
DOCKER_NET_SUBNET = "172.25.0.0/16"
DOCKER_JWK_URL = f"http://{DOCKER_NET_GATEWAY_IP}:{OIDC_PORT}/jwks"
DOCKER_DB_NAME = "MCPTestDB"
CONTAINER_NAME = f"db_container_{DOCKER_DB_NAME}"
